#!/bin/sh
set -eu
cd "$(dirname "$0")"

required_logs="
plateau_certificate.log
plateau_certificate_independent.log
direct_ap_A8.log
direct_ap_extremizer9.log
direct_ap_table_12.log
direct_ap_tests.log
staircase_criterion_1e8.log
staircase_chunk_sample.log
staircase_chunk_1e8.log
"

for file in $required_logs; do
    if [ ! -f "$file" ]; then
        echo "missing required log: $file" >&2
        exit 1
    fi
done

grep -q '^KUNZ_ASSERTIONS status=PASS$' plateau_certificate.log
grep -q '^INDEPENDENT_ASSERTIONS status=PASS$' plateau_certificate_independent.log
grep -q '^DIRECT_A8_ASSERTIONS status=PASS$' direct_ap_A8.log
grep -q '^EXTREMIZER_ASSERTIONS status=PASS$' direct_ap_extremizer9.log
grep -q '^TABLE_ASSERTIONS status=PASS$' direct_ap_table_12.log
grep -q '^UNIT_TEST_SUMMARY status=PASS$' direct_ap_tests.log
grep -q '^CRITERION_ASSERTIONS status=PASS$' staircase_criterion_1e8.log
grep -q '^CHUNK_ASSERTIONS status=PASS$' staircase_chunk_sample.log
grep -q '^CHUNK_ASSERTIONS status=PASS$' staircase_chunk_1e8.log

criterion_failures=$(sed -n 's/^CRITERION_FAILURE //p' staircase_criterion_1e8.log)
chunk_failures=$(sed -n 's/^CHUNK_FAILURE //p' staircase_chunk_1e8.log)
if [ "$criterion_failures" != "$chunk_failures" ]; then
    echo "full criterion and chunk failure lists disagree" >&2
    exit 1
fi
criterion_pairs=$(sed -n 's/.*pairs_checked=\([0-9][0-9]*\).*/\1/p' \
    staircase_criterion_1e8.log | tail -n 1)
chunk_pairs=$(sed -n 's/.*pairs_checked=\([0-9][0-9]*\).*/\1/p' \
    staircase_chunk_1e8.log | tail -n 1)
if [ -z "$criterion_pairs" ] || [ "$criterion_pairs" != "$chunk_pairs" ]; then
    echo "full criterion and chunk pair counts disagree" >&2
    exit 1
fi

temporary="CERTIFICATE.txt.tmp"
{
    echo "COMPUTATIONAL CERTIFICATE"
    echo "Arithmetic Progressions in Gap Sets of Numerical Semigroups"
    echo
    echo "This summary is generated by generate_certificate.sh from the raw"
    echo "execution logs listed below.  The script exits unsuccessfully unless"
    echo "every advertised assertion line is present with status PASS."
    echo
    echo "PLATEAU CERTIFICATE, A=9"
    grep '^KUNZ_RESULT' plateau_certificate.log
    echo
    echo "INDEPENDENT PLATEAU CROSS-CHECK"
    grep '^INDEPENDENT_RESULT' plateau_certificate_independent.log
    echo
    echo "DIRECT A=8 SEARCH"
    grep '^DIRECT_RESULT' direct_ap_A8.log
    echo
    echo "DIRECT CHECK OF THE MULTIPLICITY-9 EXTREMIZER"
    grep '^EXTREMIZER_RESULT' direct_ap_extremizer9.log
    echo
    echo "DIRECT TABLE THROUGH A=12"
    grep '^TABLE_RESULT' direct_ap_table_12.log
    echo
    echo "COMPOSITE CRITERION THROUGH A=100000000"
    grep '^CRITERION_FAILURE' staircase_criterion_1e8.log
    grep '^CRITERION_SUMMARY' staircase_criterion_1e8.log
    echo
    echo "CHUNKED SAMPLE"
    grep '^CHUNK_FAILURE' staircase_chunk_sample.log
    grep '^CHUNK_SUMMARY' staircase_chunk_sample.log
    grep '^CHUNK_ASSERTIONS' staircase_chunk_sample.log
    echo
    echo "FULL-RANGE CHUNK CROSS-CHECK"
    grep '^CHUNK_FAILURE' staircase_chunk_1e8.log
    grep '^CHUNK_SUMMARY' staircase_chunk_1e8.log
    grep '^CHUNK_ASSERTIONS' staircase_chunk_1e8.log
    echo "FULL_RANGE_CROSS_CHECK status=PASS"
    echo
    echo "UNIT TESTS"
    grep '^UNIT_TEST ' direct_ap_tests.log
    grep '^UNIT_TEST_SUMMARY' direct_ap_tests.log
} > "$temporary"
mv "$temporary" CERTIFICATE.txt
echo "wrote CERTIFICATE.txt"